{
  "currentUrl": "https://192.168.254.222:20145/index.html#/system/network",
  "testError": {
    "matcherName": "",
    "message": "Error: Promise was rejected with the following reason: Error: timeout",
    "stack": "Error: Promise was rejected with the following reason: Error: timeout\n    at timer.catch.e (/Volumes/Extreme SSD/studyjs/misc_auto/node_modules/webdriverio/build/commands/browser/waitUntil.js:71:11)",
    "passed": false,
    "expected": "",
    "actual": ""
  },
  "browserErrorlog": [
    {
      "level": "SEVERE",
      "message": "https://192.168.254.222:20145/favicon.ico - Failed to load resource: the server responded with a status of 404 (Not Found)",
      "source": "network",
      "timestamp": 1555514808268
    }
  ]
}